client/urls.py
from django.urls import re_path as url
from client import views
# SET THE NAMESPACE!
app_name = 'client'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[

    url(r'login_client/', views.login_client, name='login_client'),
    url(r'signup_client/', views.signup_client, name='signup_client'),
    url(r'register/', views.register, name='register'),
    url(r'user_login/', views.user_login, name='user_login'),
    url(r'client_home/', views.client_home, name='client_home'),
    url(r'book_slot/(?P<slot>\d+)$', views.book_slot, name='book_slot'),
    url(r'delete_slot/(?P<slot>\d+)$', views.delete_slot, name='delete_slot'),
    url(r'^client_home_spec/', views.client_home_spec, name='client_home_spec'),
    url(r'^client_home_doc/', views.client_home_doc, name='client_home_doc'),
    url(r'^client_home_chat/(?P<slot>\d+)$', views.client_home_chat, name='client_home_chat'),
    url(r'^client_home_send/', views.client_home_send, name='client_home_send'),
    url(r'delete_msgs/', views.delete_msg, name='delete_msgs'),
    url(r'upload_file/', views.upload_file, name='upload_file'),
    url(r'download_file/(?P<id>\d+)$', views.download_file, name='download_file'),
    url(r'delete_file/(?P<upload>\d+)$', views.delete_file, name='delete_file'),
    url(r'user_logout/', views.user_logout, name='user_logout')
   
]

doctor/urls.py
from django.urls import re_path as url
from doctor import views
# SET THE NAMESPACE!
app_name = 'doctor'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[

    url(r'login_doc/', views.login_doc, name='login_doc'),
    url(r'signup_doc/', views.signup_doc, name='signup_doc'),
    url(r'register/', views.register, name='register'),
    url(r'user_login/', views.user_login, name='user_login'),
    url(r'doc_home/', views.doc_home, name='doc_home'),
    url(r'add_slot/', views.add_slot, name='add_slot'),
    url(r'^confirm_booking/(?P<slot>\d+)$', views.confirm_booking, name='confirm_booking'),
    url(r'^cancel_booking/(?P<slot>\d+)$', views.cancel_booking, name='cancel_booking'),
    url(r'^delete_slot/(?P<slot>\d+)$', views.delete_slot, name='delete_slot'),
    url(r'^doc_home_slot/(?P<date>\d{4}-\d{2}-\d{2})/$', views.doc_home_slot, name='doc_home_slot'),
    url(r'^doc_home_chat/(?P<client>\d+)$', views.doc_home_chat, name='doc_home_chat'),
    url(r'^doc_home_send/', views.doc_home_send, name='doc_home_send'),
    url(r'delete_msg/', views.delete_msg, name='delete_msg'),
    url(r'user_logout/', views.user_logout, name='user_logout')
   
]

helthify/urls.py
from django.contrib import admin
from django.urls import path, include
from doctor.views import welcome
from django.conf.urls import include
from django.urls import re_path as url
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcome, name="welcome"),
    url('doctor/',include('doctor.urls')),
    url('client/',include('client.urls')),


]

doctor/models.py
from django.db import models
from client.models import Client
from django.contrib.auth.models import User

# Create your models here.
class Specialization(models.Model):
    spec = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.spec

class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    hospital = models.CharField(max_length=120)
    location = models.CharField(max_length=100)
    specialization = models.ForeignKey(Specialization, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)

class Schedule(models.Model):
    doc = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    date = models.DateField()
    start_time = models.TimeField()
    taken = models.ForeignKey(Client, related_name='taken', on_delete=models.CASCADE, null=True, blank=True)
    confirmed = models.BooleanField(default=False)
    cancelled = models.ForeignKey(Client, related_name='cancelled', on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return str(self.doc) +" "+ str(self.date)

class Message(models.Model):
    datetime = models.DateTimeField(auto_now=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    reciever = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reciever')
    message = models.CharField(max_length=250)


    def __str__(self):
        return str(self.datetime)

    

doctor/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from doctor.models import Doctor, Schedule, Specialization, Message
from client.models import Client, Uploads
from datetime import date as dt, datetime
from itertools import chain
from operator import attrgetter
from django.contrib.auth.models import User
# Create your views here.
def welcome(request):
    return render(request,'doctor/welcome.html', context={})

def login_doc(request):
    return render(request,'doctor/doc-login.html', context={})

def signup_doc(request):
    spec = Specialization.objects.all()
    return render(request,'doctor/doc-signup.html', context={'spec':spec})

def doc_home(request):
    doc = Doctor.objects.get(user=request.user)
    schedule = Schedule.objects.filter(doc=doc)
    dates = sorted(set([sc.date for sc in schedule]))
    today = Schedule.objects.filter(doc=doc, date=dt.today())
    return render(request,'doctor/doc-home.html', context={'doc':doc, 'dates':dates, 'today':today})

def doc_home_chat(request, client):
    doc = Doctor.objects.get(user=request.user)
    schedule = Schedule.objects.filter(doc=doc)
    dates = sorted(set([sc.date for sc in schedule]))
    today = Schedule.objects.filter(doc=doc, date=dt.today())
    client = Client.objects.get(id=client)
    upload = Uploads.objects.filter(client=client)
    msgs_send = Message.objects.filter(sender=request.user.id, reciever=client.user.id)
    msgs_recieved = Message.objects.filter(reciever=request.user.id, sender=client.user.id)
    msgs = sorted(chain(msgs_send, msgs_recieved), key=attrgetter('datetime'))
    return render(request,'doctor/doc-home.html', context={'upload':upload, 'doc':doc, 'dates':dates, 'today':today, 'client' :client, 'msgs':msgs})
    
def doc_home_send(request):
    if request.method == 'POST':
        client = request.POST.get('client')
        client = Client.objects.get(id=client)
        message = request.POST.get('message')
        msg = Message(sender = request.user, reciever= client.user, message=message)
        msg.save()
        print(msg)
        return HttpResponseRedirect(reverse('doctor:doc_home_chat', args=(client.id,)))

def delete_msg(request):
    if request.method == 'POST':
        client = request.POST.get('client')
        msg = request.POST.get('msg')
        msg = Message(id=msg)
        msg.delete()
        return HttpResponseRedirect(reverse('doctor:doc_home_chat', args=(client,)))



def doc_home_slot(request, date):
    doc = Doctor.objects.get(user=request.user)
    schedule = Schedule.objects.filter(doc=doc)
    dates = sorted(set([sc.date for sc in schedule]))
    slot = Schedule.objects.filter(doc=doc, date=date)
    today = Schedule.objects.filter(doc=doc, date=dt.today())
    return render(request,'doctor/doc-home.html', context={'doc':doc, 'dates':dates, 'slots':slot, 'date':date, 'today':today})

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        place = request.POST.get('place')
        hospital = request.POST.get('hospital')
        specialization = request.POST.get('specialization')
        specialization = Specialization.objects.get(id=specialization)
        if not User.objects.filter(username=username).exists():
            user = User(username=username, first_name=firstname, last_name=lastname, is_staff=1)
            user.set_password(password)
            user.save()

            doc = Doctor(user=user, location=place, hospital=hospital, specialization=specialization)
            doc.save()
            messages.success(request, "Regitration Success!")
            return HttpResponseRedirect(reverse('doctor:login_doc'))
        else:
            messages.warning(request, "Username already exist!")
            return HttpResponseRedirect(reverse('doctor:login_doc'))

        

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active and user.is_staff:
                login(request,user)
                print('working')
                return HttpResponseRedirect(reverse('doctor:doc_home'))
            else:
                messages.warning(request, "You are not a doctor")
                return HttpResponseRedirect(reverse('doctor:login_doc'))
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            messages.warning(request, "Invalid login details given")
            return HttpResponseRedirect(reverse('doctor:login_doc'))
    else:
        return HttpResponseRedirect(reverse('doctor:login_doc'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('welcome'))


def add_slot(request):
    if request.method == 'POST':
        doc = Doctor.objects.get(user=request.user)
        date = request.POST.get('date')
        start = request.POST.get('start')
        no_hours = int(request.POST.get('no_hours'))
        start =  str(datetime.strptime(str(int(start[:2])) +":"+ start[3:],"%H:%M"))[11:16]
        sc = Schedule(doc=doc, date=date, start_time=start, taken=None)
        sc.save()
        for _ in range(no_hours-1):
            start =  str(datetime.strptime(str(int(start[:2])+1) +":"+ start[3:],"%H:%M"))[11:16]
            sc = Schedule(doc=doc, date=date, start_time=start, taken=None)
            sc.save()
    return HttpResponseRedirect(reverse('doctor:doc_home_slot', args=(date,)))

def confirm_booking(request, slot):
    slot = Schedule.objects.get(id=slot)
    slot.confirmed = True
    slot.save()
    return HttpResponseRedirect(reverse('doctor:doc_home_slot', args=(slot.date,)))

def cancel_booking(request, slot):
    slot = Schedule.objects.get(id=slot)
    slot.confirmed=False
    slot.cancelled = slot.taken
    slot.taken=None
    slot.save()
    return HttpResponseRedirect(reverse('doctor:doc_home_slot', args=(slot.date,)))

def delete_slot(request, slot):
    slot = Schedule.objects.get(id=slot)
    date = slot.date
    slot.delete()
    return HttpResponseRedirect(reverse('doctor:doc_home_slot', args=(date,)))

templates/doctor/doc-login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DocHour</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body style="background-image: url('../../static/images/bg.webp');background-position: center; background-repeat: repeat;">
    <nav class="navbar navbar-expand-lg fixed-top bg-primary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="{% url 'welcome' %}"><b class="bi bi-heart-pulse-fill text-light">
                DocHour</b></a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
            <div>
                    <!-- <a class="nav-link active text-light" aria-current="page" href="#">Logout</a> -->
                 
            </div>
          </div>
        </div>
      </nav>
        
      
      <nav class="navbar bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <b class="bi bi-heart-pulse-fill text-danger">
            DocHour</b>
          </a>
        </div>
      </nav>
      <div class="container">
      <div class="row mx-auto my-auto">
        <div class="col-sm-6 mx-auto my-auto">
            <div class="card p-4 m-5">
                <div class="card-body">
                    <h5 class="card-title  text-center">
                        <a class="navbar-brand" href="#"><b class="bi bi-heart-pulse-fill text-danger">
                            DocHour</b></a>
                    </h5><br>
                    {% for message in messages %}
    
                        <div class="alert alert-success">
                            <a class="close" href="#" data-dismiss="alert"></a>
                            {{ message }}
                        </div>

                    {% endfor %}
                    
                    <form action="{% url 'doctor:user_login' %}" method="post">
                        {% csrf_token %}
                        <input type="email" name="username" class="form-control" placeholder="email ID" autofocus><br>
                        <input type="password" name="password" class="form-control" placeholder="password"><br>
                        <div class="d-grid gap-2">
                        <input type="submit" value="Login" class="btn btn-primary">
                        <a href="{% url 'doctor:signup_doc' %}" class="text-center">Register</a>
                        </div>   
                    </form>
                    
                
                </div>
            </div>
        </div>
      </div>
      </div>
      
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

templates/doctor/doc-signup.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DocHour</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body style="background-image: url('../../static/images/bg.webp');background-position: center; background-repeat: repeat;">
    <nav class="navbar navbar-expand-lg fixed-top bg-primary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#"><b class="bi bi-heart-pulse-fill text-light">
                DocHour</b></a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
            <div>
                    <!-- <a class="nav-link active text-light" aria-current="page" href="#">Logout</a> -->
                 
            </div>
          </div>
        </div>
      </nav>
        
      <nav class="navbar bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <b class="bi bi-heart-pulse-fill text-danger">
            DocHour</b>
          </a>
        </div>
      </nav>
      <div class="container">
      <div class="row mx-auto my-auto">
        <div class="col-sm-6 mx-auto my-auto">
            <div class="card p-4 m-5">
                <div class="card-body">
                    <h5 class="card-title  text-center">
                        <a class="navbar-brand" href="#"><b class="bi bi-heart-pulse-fill text-danger">
                            DocHour</b></a>
                    </h5><br>
                    {% for message in messages %}
    
                        <div class="alert alert-success">
                            <a class="close" href="#" data-dismiss="alert">×</a>
                            {{ message }}
                        </div>

                    {% endfor %}
                    
                    <form action="{% url 'doctor:register' %}" method="post">
                        {% csrf_token %}
                        <input required type="email" name="username" class="form-control" placeholder="Email ID"><br>
                        <input type="password" name="password" class="form-control" placeholder="Password" required><br>
                        <input type="text" name="firstname" class="form-control" placeholder="Firstname" required><br>
                        <input type="text" name="lastname" class="form-control" placeholder="Lastname" required><br>
                        <input type="text" name="hospital" class="form-control" placeholder="Hospital" required><br>
                        <input type="text" name="place" class="form-control" placeholder="Place" required><br>
                        <select class="form-select" aria-label="Default select example" name="specialization">
                          <option selected>select a specialization</option>
                         {% for s in spec %}
                          <option value="{{s.id}}">{{s.spec}}</option>
                          {% endfor %}
                        </select>
                        <br>
                        <div class="d-grid gap-2">
                        <input type="submit" value="Register" class="btn btn-primary">
                        </div>   
                    </form>
                    
                
                </div>
            </div>
        </div>
      </div>
      </div>
      
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

templates/doctor/welcome.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DocHour</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body style="background-image: url('../../static/images/bg.webp');background-position: center;">
    <nav class="navbar navbar-expand-lg fixed-top bg-primary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#"><b class="bi bi-heart-pulse-fill text-light">
                DocHour</b></a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
            <div>
                    <!-- <a class="nav-link active text-light" aria-current="page" href="#">Logout</a> -->
                 
            </div>
          </div>
        </div>
      </nav>
        
      
      <nav class="navbar bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <b class="bi bi-heart-pulse-fill text-danger">
            DocHour</b>
          </a>
        </div>
      </nav>
      <div class="container">
      <div class="row">
        <div class="col-sm-6 mx-auto">
            <div class="card p-3 m-5 mx-auto">
                <div class="card-body">
                    <h5 class="card-title  text-center">
                        <a class="navbar-brand" href="#"><b class="bi bi-heart-pulse-fill text-danger">
                            DocHour</b></a>
                    </h5><br> 
                    <p><b>DocHour</b> offers you  a convenient way to stay in touch with your favorite doctors around the world. Your consultation now cross borders.</p>
                    Get started by choosing type of user <br><br>
                <div class="row text-center ">
                    <div class="col-4"><a href="{% url 'client:login_client' %}" class="text-decoration-none"><div class="card p-4">
                        <i class="bi bi-person-fill fs-1"></i>
                        <b>Client</b>
                    </div></a></div>
                    <div class="col-4"><a href="{% url 'doctor:login_doc' %}" class="text-decoration-none"><div class="card p-4">
                      <i class="bi bi-person-heart fs-1"></i>
                      <b>Doctor</b>
                  </div></a></div>
                    <div class="col-4"><a href="admin/" class="text-decoration-none" target="_blank"><div class="card p-4">
                      <i class="bi bi-person-fill-gear  fs-1"></i>
                      <b>Admin</b>
                  </div></a></div>
                    
                </div>
                </div>
                </div>
            </div>
        </div>
      </div>
      </div>
      
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>