client/urls.py
from django.urls import re_path as url
from client import views
# SET THE NAMESPACE!
app_name = 'client'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[

    url(r'login_client/', views.login_client, name='login_client'),
    url(r'signup_client/', views.signup_client, name='signup_client'),
    url(r'register/', views.register, name='register'),
    url(r'user_login/', views.user_login, name='user_login'),
    url(r'client_home/', views.client_home, name='client_home'),
    url(r'book_slot/(?P<slot>\d+)$', views.book_slot, name='book_slot'),
    url(r'delete_slot/(?P<slot>\d+)$', views.delete_slot, name='delete_slot'),
    url(r'^client_home_spec/', views.client_home_spec, name='client_home_spec'),
    url(r'^client_home_doc/', views.client_home_doc, name='client_home_doc'),
    url(r'^client_home_chat/(?P<slot>\d+)$', views.client_home_chat, name='client_home_chat'),
    url(r'^client_home_send/', views.client_home_send, name='client_home_send'),
    url(r'delete_msgs/', views.delete_msg, name='delete_msgs'),
    url(r'upload_file/', views.upload_file, name='upload_file'),
    url(r'download_file/(?P<id>\d+)$', views.download_file, name='download_file'),
    url(r'delete_file/(?P<upload>\d+)$', views.delete_file, name='delete_file'),
    url(r'user_logout/', views.user_logout, name='user_logout')
   
]

doctor/urls.py
from django.urls import re_path as url
from doctor import views
# SET THE NAMESPACE!
app_name = 'doctor'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[

    url(r'login_doc/', views.login_doc, name='login_doc'),
    url(r'signup_doc/', views.signup_doc, name='signup_doc'),
    url(r'register/', views.register, name='register'),
    url(r'user_login/', views.user_login, name='user_login'),
    url(r'doc_home/', views.doc_home, name='doc_home'),
    url(r'add_slot/', views.add_slot, name='add_slot'),
    url(r'^confirm_booking/(?P<slot>\d+)$', views.confirm_booking, name='confirm_booking'),
    url(r'^cancel_booking/(?P<slot>\d+)$', views.cancel_booking, name='cancel_booking'),
    url(r'^delete_slot/(?P<slot>\d+)$', views.delete_slot, name='delete_slot'),
    url(r'^doc_home_slot/(?P<date>\d{4}-\d{2}-\d{2})/$', views.doc_home_slot, name='doc_home_slot'),
    url(r'^doc_home_chat/(?P<client>\d+)$', views.doc_home_chat, name='doc_home_chat'),
    url(r'^doc_home_send/', views.doc_home_send, name='doc_home_send'),
    url(r'delete_msg/', views.delete_msg, name='delete_msg'),
    url(r'user_logout/', views.user_logout, name='user_logout')
   
]

helthify/urls.py
from django.contrib import admin
from django.urls import path, include
from doctor.views import welcome
from django.conf.urls import include
from django.urls import re_path as url
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcome, name="welcome"),
    url('doctor/',include('doctor.urls')),
    url('client/',include('client.urls')),


]

client/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    place = models.CharField(max_length=100)
    age = models.IntegerField()
    health_history = models.CharField(max_length=250)

    def __str__(self):
        return str(self.user.first_name)

class Uploads(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    link = models.FileField(upload_to='media/uploads/')
    filename = models.CharField(max_length=150)
    caption = models.CharField(max_length=150)
    date_of_issue = models.DateField()
    def __str__(self) -> str:
        return str(self.client)

client/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, FileResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from client.models import Client, Uploads
from doctor.models import Schedule, Specialization, Doctor, Message
from datetime import date as dt, datetime, timedelta
from django.contrib.auth.models import User
from itertools import chain
from operator import attrgetter
from django.core.files.storage import FileSystemStorage
import time
import mimetypes
import os
# Create your views here.

def login_client(request):
    return render(request,'client/client-login.html', context={})

def signup_client(request):
    return render(request,'client/client-signup.html', context={})

def client_home(request):
    client = Client.objects.get(user=request.user)
    today = Schedule.objects.filter(taken=client, date = dt.today())
    booked = Schedule.objects.filter(taken=client)
    cancelled = Schedule.objects.filter(cancelled=client)
    spec = Specialization.objects.all()
    uploads = Uploads.objects.filter(client=client)
    return render(request,'client/client-home.html', context={'uploads':uploads, 'client': client, 'booked':booked,'cancelled':cancelled, 'spec':spec, 'today': today})

def client_home_chat(request, slot):
    doctor = 0
    slot = Schedule.objects.get(id=slot)
    msgs = ['wait until your scheduled time to start chat']
    client = Client.objects.get(user=request.user)
    today = Schedule.objects.filter(taken=client, date = dt.today())
    booked = Schedule.objects.filter(taken=client)

    start = datetime.strptime(str(slot.date)+" "+str(int(str(slot.start_time)[:2])) +":"+ str(slot.start_time)[3:5],"%Y-%m-%d %H:%M")
    if int(str(slot.start_time)[:2])!=23:
        end = datetime.strptime(str(slot.date)+" "+str(int(str(slot.start_time)[:2])+1) +":"+ str(slot.start_time)[3:5],"%Y-%m-%d %H:%M")
    else:
        end = datetime.strptime(str(slot.date + timedelta(days=1))+" 00:"+ str(slot.start_time)[3:5],"%Y-%m-%d %H:%M")
    now = datetime.strptime(str(datetime.now())[0:16], "%Y-%m-%d %H:%M")
    if slot.date == dt.today() and now >= start and now <= end:
        doctor = Doctor.objects.get(id=slot.doc.id)
        msgs_recieved = Message.objects.filter(sender=request.user.id, reciever=doctor.user.id)
        msgs_send = Message.objects.filter(reciever=request.user.id, sender=doctor.user.id)
        msgs = sorted(chain(msgs_send, msgs_recieved), key=attrgetter('datetime'))
    elif slot.date == dt.today() and now > end:
        msgs =["Schedule ended at " + str(end)[11:16]]
    elif slot.date == dt.today() and now < start:
        msgs =["Schedule is from " + str(start)[11:16] + " to " + str(end)[11:16] ]
    cancelled = Schedule.objects.filter(cancelled=client)
    spec = Specialization.objects.all()
    uploads = Uploads.objects.filter(client=client)
    
    return render(request,'client/client-home.html', context={'uploads':uploads, 'slot':slot, 'client': client, 'booked':booked,'cancelled':cancelled, 'spec':spec, 'today': today, 'doctor':doctor, 'msgs': msgs})


def client_home_spec(request):
    specs=""
    if request.method == 'POST':
        specs = request.POST.get('spec')
    client = Client.objects.get(user=request.user)
    booked = Schedule.objects.filter(taken=client)
    today = Schedule.objects.filter(taken=client, date = dt.today())
    cancelled = Schedule.objects.filter(cancelled=client)
    spec = Specialization.objects.all()
    spec_sel = Specialization.objects.get(id=specs)
    doc = Doctor.objects.filter(specialization=spec_sel)
    uploads = Uploads.objects.filter(client=client)
    return render(request,'client/client-home.html', context={'uploads':uploads, 'client': client, 'booked':booked, 'cancelled':cancelled, 'spec_sel':spec_sel,'spec':spec, 'doctors':doc,  'today': today})

def client_home_doc(request):
    specs=""
    docs=""
    if request.method == 'POST':
        specs = request.POST.get('spec_sel')
        docs = request.POST.get('doc')
    client = Client.objects.get(user=request.user)
    booked = Schedule.objects.filter(taken=client)
    today = Schedule.objects.filter(taken=client, date = dt.today())
    cancelled = Schedule.objects.filter(cancelled=client)
    spec = Specialization.objects.all()
    spec_sel = Specialization.objects.get(spec=specs)
    doc = Doctor.objects.filter(specialization=spec_sel)
    doctor = Doctor.objects.get(id=docs)
    doc_schedule = Schedule.objects.filter(doc=doctor)
    for sc in doc_schedule:
        if sc.date < dt.today() :
            sc.delete()
    doc_schedule = Schedule.objects.filter(doc=doctor)
    uploads = Uploads.objects.filter(client=client)
    return render(request,'client/client-home.html', context={'uploads':uploads, 'client': client, 'booked':booked, 'cancelled':cancelled, 'spec_sel':spec_sel,'spec':spec, 'doctors':doc, 'doc_schedule':doc_schedule, 'doctor':doctor,  'today': today})

def client_home_send(request):
    if request.method == 'POST':
        doc = request.POST.get('doctor')
        doc = Doctor.objects.get(id=doc)
        slot = request.POST.get('slot')
        slot = Schedule.objects.get(id=slot)
        message = request.POST.get('message')
        msg = Message(sender = request.user, reciever= doc.user, message=message)
        msg.save()
        return HttpResponseRedirect(reverse('client:client_home_chat', args=(slot.id,)))

def delete_msg(request):
    if request.method == 'POST':
        slot = request.POST.get('slot')
        msg = request.POST.get('msg')
        msg = Message(id=msg)
        msg.delete()
        return HttpResponseRedirect(reverse('client:client_home_chat', args=(slot,)))

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        place = request.POST.get('place')
        age = request.POST.get('age')
        health_history = request.POST.get('health-history')
        if not User.objects.filter(username=username).exists():
            user = User(username=username, first_name=firstname, last_name=lastname)
            user.set_password(password)
            user.save()
            
            client = Client(user=user, place=place, age=age, health_history=health_history)
            client.save()
            messages.success(request, "Regitration Success!")
            return HttpResponseRedirect(reverse('client:login_client'))
        else:
            messages.warning(request, "Username already exist!")
            return HttpResponseRedirect(reverse('client:login_client'))


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active and not user.is_staff:
                login(request,user)
                return HttpResponseRedirect(reverse('client:client_home'))
            else:
                messages.warning(request, "You are not a client")
                return HttpResponseRedirect(reverse('client:login_client'))
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            messages.warning(request, "Invalid login details given")
            return HttpResponseRedirect(reverse('client:login_client'))
    else:
        return HttpResponseRedirect(reverse('client:login_client'))

def book_slot(request, slot):
    user= User.objects.get(id = request.user.id)
    slot= Schedule.objects.get(id = slot)
    client = Client.objects.get(user=user)
    slot.taken = client
    slot.confirmed = False
    slot.save()
    return HttpResponseRedirect(reverse('client:client_home'))

def delete_slot(request, slot):
    slot = Schedule.objects.get(id=slot)
    slot.delete()
    return HttpResponseRedirect(reverse('client:client_home'))

def delete_file(request, upload):
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    upload = Uploads.objects.get(id=upload)
    filepath = BASE_DIR + "".join([c if c != '/' else '\\' for c in upload.link.url[6:]])
    print(filepath)
    if os.path.exists(filepath):
        os.remove(filepath)
        upload.delete()
    
    return HttpResponseRedirect(reverse('client:client_home'))


def upload_file(request):
    if request.method == 'POST' and request.FILES['link']:
        filen = request.POST.get("filename")
        link = request.FILES['link']
        link.name = ''.join([c if c!=' ' else '-' for c in link.name])
        fs = FileSystemStorage()
        filename = fs.save(link.name, link)
        uploaded_file_url = fs.url(filename)
        date_of_issue = request.POST.get('date_of_issue')
        client = Client.objects.get(user=request.user)
        upload = Uploads(filename=link.name, caption=filen, link=uploaded_file_url, date_of_issue=date_of_issue, client=client)
        upload.save()
        return HttpResponseRedirect(reverse('client:client_home'))

def download_file(request, id):
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    upload= Uploads.objects.get(id=id)
    paths = upload.link.url
    filepath = BASE_DIR + "".join([c if c != '/' else '\\' for c in paths[6:]])
    with open(filepath, 'rb') as f:
        path = f.read()
    mime_type, _ = mimetypes.guess_type(filepath)
    response = HttpResponse(path, content_type=mime_type)
    # Set the HTTP header for sending to browser
    response['Content-Disposition'] = "attachment; filename=%s" % upload.filename
    # Return the response value
    return response

@login_required
def user_logout(request):
    logout(request)

templates/client/client-home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DocHour</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body style="background-image: url('../../../static/images/bg.webp');background-repeat: repeat; background-position: center; ">
    
    
    <nav class="navbar navbar-expand-lg fixed-top bg-primary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#"><b class="bi bi-heart-pulse-fill text-light">
                DocHour</b></a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <a class="nav-link text-light rounded-pill border" data-bs-toggle="modal" data-bs-target="#file-upload"> <b class="bi bi-folder-fill"> File Upload</b>  </a>

              
            </ul>
            <div>
                    <a class="nav-link active text-light" aria-current="page" href="{% url 'doctor:user_logout' %}">Logout</a>
                 
            </div>
          </div>
        </div>
      </nav>
        
      <!-- Modal -file upload -->
      <div class="modal fade" id="file-upload" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">File upload</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form action="{% url 'client:upload_file' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="link" class="form-control" required>
                <input type="date" name="date_of_issue" placeholder="Date of issue" class="form-control" required>
                <div class="row">
                  <div class="col-9">
                    <input type="text" name="filename" placeholder="Document name" class="form-control" required >
                  </div>
                  <div class="col-3">
                    <input type="submit" value="upload" class="form-control bg-info" required>
                  </div>
                </div>
              </form>
              <br>
              <table class="table">
                <tr>
                  <th scope="col">Document</th>
                  <th scope="col">Date of issue</th>
                  <th></th>

                </tr>

                {% for f in uploads %}
                <tr>
                  <td scope="col"><a href="{% url 'client:download_file' f.id %}">{{f.caption}}</a></td>
                  <td scope="col">{{f.date_of_issue}}</td>
                  <td scope="col"><a href="{% url 'client:delete_file' f.id %}"><i class="bi bi-trash-fill text-danger"></i></a></td>

                </tr>
                {% endfor %}
              </table>
               </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>
      <nav class="navbar bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <b class="bi bi-heart-pulse-fill text-danger">
            DocHour</b>
          </a>
        </div>
      </nav>
      <br>
      <div class="container">
      <div class="row">
      
        <div class="col-sm-3 mx-auto p-3 border bg-light rounded">
          <p class="bg-primary rounded-pill text-white text-center p-1"><b>Book a slot</b></p>
          <form action="{% url 'client:client_home_spec' %}" method="post">
            {% csrf_token %}
          <select class="form-select" aria-label="Default select example" onchange="this.form.submit()" name="spec">
            <option selected>{% if spec_sel %}{{spec_sel}}{% else %} Select specialization {% endif %}</option>
            {% for s in spec %}
            <option value="{{s.id}}">{{s.spec}}</option>
            {% endfor %}
          </select>
        </form>

        <form action="{% url 'client:client_home_doc' %}" method="post">
          {% csrf_token %}
          <select class="form-select" aria-label="Default select example"  onchange="this.form.submit()" name="doc">
            <option selected>{% if doctor %}{{doctor.user.first_name}} {{doctor.user.last_name}}{% else %} Select doctor {% endif %}</option>
            {% for d in doctors %}
            <option value="{{d.id}}">Dr. {{d.user.first_name}} {{d.user.last_name}}</option>
            {% endfor %}
          </select>
          <input type="hidden" name="spec_sel" value="{{spec_sel}}">
        </form>
        <br>
        <ul class="list-group text-start"  style="overflow-y: auto; height:400px">
          {% for slot in doc_schedule  %}
          {% if  slot.taken %}<li class="list-group-item text-center" style="background-color: rgb(235, 194, 194);">{{slot.date}} - {{slot.start_time}} <span class="badge bg-danger rounded-pill">Taken</span>
          {% else %}<li class="list-group-item text-center" style="background-color: rgb(210, 240, 192);">{{slot.date}} - {{slot.start_time}} <a href="" data-bs-toggle="modal" data-bs-target="#Schedule{{ forloop.counter }}"><span class="badge bg-success rounded-pill">BOOK NOW</span></a>
            <!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" id="Schedule{{ forloop.counter }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Confirm slot</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Confirm booking of your slot with <b>Dr. {{slot.doc.user.first_name}} {{slot.doc.user.last_name}}</b> on <b>{{slot.date}}</b> at <b>{{slot.start_time}}</b> ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="{% url 'client:book_slot' slot.id %}">Confirm</a>
      </div>
    </div>
  </div>
</div>
          {% endif %}
          </li>
          {% endfor %}
          <br>

        </ul>
        </div>

        <div class="col-sm-4 mx-auto px-4 py-2 text-center rounded border bg-white" >
          <div class="card mx-2 bg-light">
            <div class="card-header bg-primary text-light">
              Profile
            </div>
          <p class="text-start p-3">
          Name: <b>{{client.user.first_name}} {{client.user.last_name}}</b><br>
          Age: <b> {{client.age}} </b><br>
          Place: <b>{{client.place}} </b><br>
          Health history: <b>{{client.health_history}}</b></p>
          </div>
          
          <div class="card m-2 bg-light">
            <div class="card-header bg-primary text-light">Booked Slots</div>
              <div class="card-body">
                
                <script>
                  
                </script>
                <ul class="list-group text-start"  style="overflow-y: auto; height:300px">
                  {% for slot in booked %}
                  {% if slot.confirmed %}<li class="list-group-item text-center" style="background-color: rgb(187, 221, 154);">{{slot.date}} {{slot.start_time}} <br> <b>Dr. {{slot.doc.user.first_name}} {{slot.doc.user.last_name}}</b> <br> 
                    {% if slot in today%}<span class="badge rounded-pill bg-success">  Today </span>
                    <a href="{% url 'client:client_home_chat' slot.id %}"><span class="badge rounded-pill bg-success">  Start chat </span></a>
                    {% else %}
                    <span class="badge rounded-pill bg-success"> Confirmed by doctor </span>{% endif %}</li>
                  {% else %}<li class="list-group-item text-center"  style="background-color: rgb(228, 233, 182);">{{slot.date}} {{slot.start_time}} <br> <b> Dr. {{slot.doc.user.first_name}} {{slot.doc.user.last_name}}</b> <br> <span class="badge rounded-pill bg-warning text-dark">waiting for confirmation</span></li>
                  {% endif %}
                  {% endfor %}

                  {% for slot in cancelled %}
                  <li class="list-group-item text-center"  style="background-color: rgb(233, 196, 182);">{{slot.date}} {{slot.start_time}} <br> <b> Dr. {{slot.doc.user.first_name}} {{slot.doc.user.last_name}}</b> <br> 
                    <span class="badge rounded-pill bg-danger">cancelled by doctor</span> <a href="{% url 'client:delete_slot' slot.id %}"><span class="badge rounded-pill bg-danger"><i class="bi bi-trash-fill"></i></span></a></li>
                  {% endfor %}
                  <br>

                </ul>
              
              </div>
            </div>
      </div>

        <div class="col-sm-5 mx-auto p-3 border bg-white rounded">

            <div class="card mb-2">
                <div class="row  p-3">
                <div class="col-sm-2 text-center my-auto">
                    <i class="bi bi-person-circle fs-2"></i>
                </div>
                <div class="col-sm-9 my-auto">
                  <div class="row">
                    <div class="col-10">
                      <b>{% if doctor %}Dr. {{doctor.user.first_name}} {{doctor.user.last_name}}{% endif %}</b>
                    </div>
                    <div class="col-2 my-auto">
                      <span class="badge text-bg-secondary rounded-circle fs-6"> <i class="bi bi-camera-video-fill"></i></span>
                    </div>
                  </div>
                    

                </div>
                </div>

            </div>
        
        <script>
          function scrollbottom() {
            
          var chatHistory = document.getElementById("msgbox");
          chatHistory.scrollTo(0, nestedElement.scrollHeight);
        }

        </script>
        <div class="px-3" style="overflow-y: auto; height:400px" id="msgbox">
          {% for m in msgs %}
          {% if doctor == 0 %}
          <p class="text-center"><span class="badge bg-secondary p-2 rounded-pill mt-4">{{msgs.0}}</span></p>
          {% else %}
          {% if not m.sender.is_staff %}
          <div class="dropdown text-end">
            <small><small><small>{{m.datetime}}</small></small></small><br>
            <button class="dropdown-toggle bg-dark text-light badge rounded-pill" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{m.message}}
            </button>
            <ul class="dropdown-menu text-center text-dark">
              
              <form action="{% url 'client:delete_msgs' %}" method="post">
                {% csrf_token %}
              <input type="hidden" name="msg" value="{{m.id}}">
              <input type="hidden" name="slot" value="{{slot.id}}">
              <button type="submit" class="btn">Delete message</button>
            </form>
            </ul>
          </div>
            {% else %}
            <div class=""><small><small><small>{{m.datetime}}</small></small></small><br><span class="badge text-bg-secondary  rounded-pill px-3 py-2">{{m.message}}</span></div>
            {% endif %}
            {% endif %}
          {% empty %}
          <p class="text-center"><span class="badge rounded-pill text-bg-secondary px-3 py-2">{% if client %} No messages yet! {% else %} Select a client to start chat. {% endif %}</span></p>
          
          {% endfor %}
        </div>

        <div class="row mt-4 mx-auto">
          {% if doctor != 0 %}
          <div class="col-10">
            
            <form action="{% url 'client:client_home_send' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="doctor" value="{{doctor.id}}">
              <input type="hidden" name="slot" value="{{slot.id}}">
              <input class="form-control rounded-pill" name="message" type="text" placeholder="Enter message to send" aria-label="Enter message to send" onformchange="this.form.submit(); " autofocus>
          </div>
          <div class="col-2"> 
              <button type="submit" class="rounded-circle btn btn-dark mr-0"><i class="bi bi-send-fill"></i></button>
          </div>
        </form>
        {% else %}
        {% endif %}

        </div>
            
       


        </div>
      </div>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>